version: "3"

volumes:
  tableau_data:
    external: false

services:
  tableau:
    container_name: tableau-server
    image: <tableau image from builder>
    restart: always
    user: tableau
    ports:
      - "8080:8080"
      - "8850:8850"
    environment:
      - TABLEAU_USERNAME="admin"
      - TABLEAU_PASSWORD="tableau"
      - TSM_REMOTE_UID=1010
      - TSM_REMOTE_USERNAME="tsm"
      - TSM_REMOTE_PASSWORD="<strong passwd>"
      - LICENSE_KEY="XXXXXXXXXXXX"
    volumes:
      - tableau_data:/var/opt/tableau